hapidocweb:
  build: .
  stdin_open: true # this is the -i flag in docker run
  tty: true # this is the -t flag in docker run
  ports:
      - "8080:8080"
  environment:
    MONGO_DB_HOST: "mongo"
    MONGO_DB_PORT: "27017"
    HAPIDOC_WEB_HOST: "0.0.0.0"
    HAPIDOC_WEB_PORT: "8080"
    HAPIDOC_WEB_PASS: "12345"
  external_links:
    - mongo:mongo
